#########################
### BASIC INFORMATION ###
#########################

# The name of the site.
# Written in big on top of the hero image, and used in page titles.
name: OFFERINGS

# A subtitle for the site.
# Written below the site's name, and next to it in the page title.
subtitle: by Steve Dondley
subtitle_html: by <span title="Steve Dondley">Steve Dondley</span>

# A default description for the site.
# Used by search engines, Facebook and Twitter. Overridden by blog posts' description when possible.
description: "A (mostly) technical blog for offering understanding, solutions, ideas and other thoughts."

# Your website URL
# Used in sitemap.xml and feed.xml
url: https://steve.dondley.com

# Information about the author. Used in feed.xml
author:
  name: Steve Dondley
  email: s@dondley.com
  url: https://steve.dondley.com

# Your disqus shortname. Entering this will enable commenting on posts by default
#disqus: kjaermaxime

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
#google_analytics: UA-59915030-2

# Data for the hero image
hero:
  image: /images/hero/laugh.jpg # The relative path to the default hero image
  fallback-color: "#d3dbe7" # The fallback color that will be used behind the image
  breakpoints: # Responsive image breakpoints. Important that these be in decreasing order!
    - 1440px
    - 1200px
    - 800px
    - 550px
    - 380px

# The URL of your GitHub repo
github: https://github.com/sdondley/sdondley.github.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

##############################
### ADVANCED OPTIONS BELOW ###
##############################

permalink: /:title/
excerpt_separator: "<!--"

collections:
  notes:
    output: true
    permalink: /:title/
    sort_by: title
  unlisted:
    output: true

sass:
  sass_dir: _sass
  style: :compressed # Can also be :expanded

# Use the following gems when building the site
plugins:
  - jekyll-sitemap # Automatically create a sitemap on build
  - jekyll-feed # Automatically create an RSS feed on build
  - jekyll-mathjax-csp # Server-side rendering of math with MathJax
  - jekyll-diagrams # Server-side rendering of graphs with Graphviz
  - jekyll-block

feed:
  excerpt_only: true

mathjax_csp:
  output: CommonHTML # SVG, CommonHTML, or MML (default: SVG)
  single_dollars: true # allow single dollar delimiters for inline math (default: false)
  ex_size: 10
  strip_css: false

defaults:
  - scope:
      type: posts
    values:
      layout: post
      published: true
      comments: true
      edited: false
  - scope:
      type: notes
    values:
      layout: post
      published: true
      comments: true
      edited: true

# Exclude these files from your production _site
exclude:
  - Rakefile
  - gulpfile.js
  - LICENSE
  - nohup.out
  - npm-debug.log
  - package.json
  - package-lock.json
  - .git
  - README.md
  - serve.bat
  - zopfli
