<<<<<<< HEAD
#########################
### BASIC INFORMATION ###
#########################

# The name of the site.
# Written in big on top of the hero image, and used in page titles.
name: OUTPUT

# A subtitle for the site.
# Written below the site's name, and next to it in the page title.
subtitle: The blog of Maxime Kjaer
subtitle_html: The blog of <span title="/maksim ˈkjɛɹ/">Maxime Kjaer</span>

# A default description for the site.
# Used by search engines, Facebook and Twitter. Overridden by blog posts' description when possible.
description: "Maxime Kjaer's blog posts about the Web, software & technology. Most likely in that order."

# Your website URL
# Used in sitemap.xml and feed.xml
url: https://kjaer.io

# Information about the author. Used in feed.xml
author:
  name: Maxime Kjaer
  email: maxime.kjaer@gmail.com
  twitter: maximekjaer
  url: https://kjaer.io

# Your disqus shortname. Entering this will enable commenting on posts by default
disqus: kjaermaxime

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-59915030-2

# Data for the hero image
hero:
  image: /images/hero/trees.jpg # The relative path to the default hero image
  fallback-color: "#d3dbe7" # The fallback color that will be used behind the image
  breakpoints: # Responsive image breakpoints. Important that these be in decreasing order!
    - 1440px
    - 1200px
    - 800px
    - 550px
    - 380px

# The URL of your GitHub repo
github: https://github.com/MaximeKjaer/kjaer.io

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

##############################
### ADVANCED OPTIONS BELOW ###
##############################

permalink: /:title/
excerpt_separator: "<!--"

collections:
  notes:
    output: true
    permalink: /:title/
    sort_by: title
  unlisted:
    output: true

sass:
  sass_dir: _sass
  style: :compressed # Can also be :expanded

# Use the following gems when building the site
plugins:
  - jekyll-sitemap # Automatically create a sitemap on build
  - jekyll-feed # Automatically create an RSS feed on build
  - jekyll-mathjax-csp # Server-side rendering of math with MathJax
  - jekyll-diagrams # Server-side rendering of graphs with Graphviz
  - jekyll-block

feed:
  excerpt_only: true

mathjax_csp:
  output: CommonHTML # SVG, CommonHTML, or MML (default: SVG)
  single_dollars: true # allow single dollar delimiters for inline math (default: false)
  ex_size: 10
  strip_css: false

defaults:
  - scope:
      type: posts
    values:
      layout: post
      published: true
      comments: true
      edited: false
  - scope:
      type: notes
    values:
      layout: post
      published: true
      comments: true
      edited: true

# Exclude these files from your production _site
exclude:
  - Rakefile
  - gulpfile.js
  - LICENSE
  - nohup.out
  - npm-debug.log
  - package.json
  - package-lock.json
  - .git
  - README.md
  - serve.bat
  - zopfli
=======
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Offerings: A blog by Steve Dondley"
email: s@dondley.com
description: >- # this means to ignore newlines until "baseurl:"
  A blog for sharing contributions with mostly technical people.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  sdondley

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
>>>>>>> f887033... move files to root
